const { DataTypes } = require("sequelize");
const sequelize = require("../config/db");

// Implements FR4.1 (Personalized Recommendations). Each row is a scored
// match between a student and an Opportunity, generated by
// services/recommendationEngine.js — mirrors the Recommendation class
// (score, type) in Appendix B.2's Class Diagram.
const Recommendation = sequelize.define(
  "Recommendation",
  {
    id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
    score: { type: DataTypes.FLOAT, allowNull: false },
    type: { type: DataTypes.STRING, defaultValue: "opportunity" },
    reason: { type: DataTypes.TEXT, defaultValue: "" },
  },
  { tableName: "recommendations", timestamps: true }
);

module.exports = Recommendation;
