import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api";
import { useAuth } from "../context/AuthContext";
import OpportunityCard from "../components/OpportunityCard";

export default function Dashboard() {
  const { user } = useAuth();
  const [recommendations, setRecommendations] = useState([]);
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    async function load() {
      try {
        const [rec, dash] = await Promise.all([api.getRecommendations(), api.dashboard()]);
        setRecommendations(rec.recommendations);
        setSummary(dash);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }
    load();
  }, []);

  return (
    <div className="page">
      <h1>Welcome back, {user?.name?.split(" ")[0]} 👋</h1>
      <p className="muted">Here's your personalized STEM Access dashboard.</p>

      {error && <div className="alert-error">{error}</div>}

      {summary && (
        <div className="stat-row">
          <div className="stat-card">
            <span className="stat-value">{summary.totalApplications}</span>
            <span className="stat-label">Applications tracked</span>
          </div>
          <div className="stat-card">
            <span className="stat-value">{summary.counts?.saved || 0}</span>
            <span className="stat-label">Saved opportunities</span>
          </div>
          <div className="stat-card">
            <span className="stat-value">{summary.counts?.applied || 0}</span>
            <span className="stat-label">Applied</span>
          </div>
          <div className="stat-card">
            <span className="stat-value">{recommendations.length}</span>
            <span className="stat-label">New recommendations</span>
          </div>
        </div>
      )}

      <div className="section-header">
        <h2>Recommended for you</h2>
        <Link to="/opportunities">Browse all opportunities →</Link>
      </div>
      <p className="muted small">
        Generated by the AI Recommendation Engine (FR4.1) from your profile's skills, interests, and career goal.{" "}
        <Link to="/profile">Update your profile</Link> to improve these.
      </p>

      {loading ? (
        <p>Loading recommendations...</p>
      ) : recommendations.length === 0 ? (
        <div className="empty-state">
          <p>No recommendations yet — complete your profile with skills and interests to get personalized matches.</p>
          <Link className="btn-primary-sm" to="/profile">
            Complete your profile
          </Link>
        </div>
      ) : (
        <div className="grid">
          {recommendations.map((r) => (
            <OpportunityCard key={r.opportunity.id} opportunity={r.opportunity} reason={r.reason} />
          ))}
        </div>
      )}
    </div>
  );
}
